# Generated by Django 4.1.6 on 2023-02-20 05:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, null='-')),
                ('minHeight', models.IntegerField(null=0)),
                ('maxHeight', models.IntegerField(null=0)),
                ('minLife', models.IntegerField(null=0)),
                ('maxLife', models.IntegerField(null=0)),
                ('traits', models.CharField(max_length=200)),
                ('health', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, null='-')),
                ('city', models.CharField(max_length=45, null='-')),
                ('email', models.EmailField(max_length=254, null='-')),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('membershipdate', models.DateField(null=datetime.date(2023, 2, 19))),
                ('photo', models.ImageField(null='images/people/noProfilephoto.png', upload_to='images/people/')),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, null='-')),
                ('color', models.CharField(max_length=15)),
                ('dob', models.DateField(null=datetime.date(2023, 2, 19))),
                ('photo', models.ImageField(null='images/dogs/nophoto.png', upload_to='images/dogs/')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.breed')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
    ]
